import { Doctor, Patient } from '@/types';

export const doctors: Doctor[] = [
  {
    id: "doctor-1",
    fullName: "Иван Петров",
    specialization: "Кардиолог",
    experience: 12,
    isAvailable: true,
    email: "PetrovI@hospital.com",
    gender: "male",
  },
  {
    id: "doctor-2",
    fullName: "Анна Соколова",
    specialization: "Терапевт",
    experience: 7,
    isAvailable: false,
    email: "SokolovaA@hospital.com",
    gender: "female",
  },
  {
    id: "doctor-3",
    fullName: "Сергей Волков",
    specialization: "Хирург",
    experience: 15,
    isAvailable: true,
    email: "VolkovS@hospital.com",
    gender: "male",
  },
  {
    id: "doctor-4",
    fullName: "Мария Новикова",
    specialization: "Невролог",
    experience: 9,
    isAvailable: true,
    email: "NovikovaM@hospital.com",
    gender: "female",
  },
  {
    id: "doctor-5",
    fullName: "Алексей Громов",
    specialization: "Эндокринолог",
    experience: 5,
    isAvailable: false,
    email: "GromovA@hospital.com",
    gender: "male",
  },
  {
    id: "doctor-6",
    fullName: "Ольга Васильева",
    specialization: "Педиатр",
    experience: 11,
    isAvailable: true,
    email: "VasilevaO@hospital.com",
    gender: "female",
  },
  {
    id: "doctor-7",
    fullName: "Павел Морозов",
    specialization: "Офтальмолог",
    experience: 8,
    isAvailable: true,
    email: "MorozovP@hospital.com",
    gender: "male",
  },
  {
    id: "doctor-8",
    fullName: "Татьяна Белова",
    specialization: "Дерматолог",
    experience: 6,
    isAvailable: false,
    email: "BelovaT@hospital.com",
    gender: "female",
  },
  {
    id: "doctor-9",
    fullName: "Константин Егоров",
    specialization: "Уролог",
    experience: 14,
    isAvailable: true,
    email: "EgorovK@hospital.com",
    gender: "male",
  },
  {
    id: "doctor-10",
    fullName: "Светлана Павлова",
    specialization: "Гастроэнтеролог",
    experience: 10,
    isAvailable: true,
    email: "PavlovaS@hospital.com",
    gender: "female",
  },
];

export const patients: Patient[] = [
  {
    id: "patient-1",
    fullName: "Максим Иванов",
    age: 58,
    diagnosis: "Гипертония",
    admittedAt: "2026-05-25",
    isCritical: true,
    doctorId: "doctor-1",
    notes: "Повышенное давление",
  },
  {
    id: "patient-2",
    fullName: "Анна Кузнецова",
    age: 32,
    diagnosis: "ОРВИ",
    admittedAt: "2026-05-24",
    isCritical: false,
    doctorId: "doctor-2",
  },
  {
    id: "patient-3",
    fullName: "Дмитрий Орлов",
    age: 45,
    diagnosis: "Хронический бронхит",
    admittedAt: "2026-05-20",
    isCritical: false,
    doctorId: "doctor-2",
  },
  {
    id: "patient-4",
    fullName: "Елена Смирнова",
    age: 27,
    diagnosis: "Мигрень",
    admittedAt: "2026-05-22",
    isCritical: false,
    doctorId: "doctor-4",
    notes: "Частые приступы",
  },
  {
    id: "patient-5",
    fullName: "Николай Фёдоров",
    age: 63,
    diagnosis: "Сахарный диабет",
    admittedAt: "2026-05-18",
    isCritical: true,
    doctorId: "doctor-5",
    notes: "Инсулинозависимый",
  },
  {
    id: "patient-6",
    fullName: "Игорь Семёнов",
    age: 41,
    diagnosis: "Пневмония",
    admittedAt: "2026-05-17",
    isCritical: false,
    doctorId: "doctor-2",
  },
  {
    id: "patient-7",
    fullName: "Виктория Лебедева",
    age: 36,
    diagnosis: "Астма",
    admittedAt: "2026-05-15",
    isCritical: false,
    doctorId: "doctor-1",
  },
  {
    id: "patient-8",
    fullName: "Артём Зайцев",
    age: 29,
    diagnosis: "Аппендицит",
    admittedAt: "2026-05-14",
    isCritical: true,
    doctorId: "doctor-3",
  },
  {
    id: "patient-9",
    fullName: "Оксана Миронова",
    age: 52,
    diagnosis: "Остеохондроз",
    admittedAt: "2026-05-13",
    isCritical: false,
    doctorId: "doctor-4",
  },
  {
    id: "patient-10",
    fullName: "Михаил Крылов",
    age: 61,
    diagnosis: "Язвенная болезнь",
    admittedAt: "2026-05-12",
    isCritical: false,
    doctorId: "doctor-10",
  },
  {
    id: "patient-11",
    fullName: "Дарья Власова",
    age: 22,
    diagnosis: "Дерматит",
    admittedAt: "2026-05-11",
    isCritical: false,
    doctorId: "doctor-8",
  },
  {
    id: "patient-12",
    fullName: "Андрей Титов",
    age: 47,
    diagnosis: "Катаракта",
    admittedAt: "2026-05-10",
    isCritical: false,
    doctorId: "doctor-7",
  },
  {
    id: "patient-13",
    fullName: "Наталья Романова",
    age: 34,
    diagnosis: "Гастрит",
    admittedAt: "2026-05-09",
    isCritical: false,
    doctorId: "doctor-10",
  },
  {
    id: "patient-14",
    fullName: "Владимир Киселёв",
    age: 68,
    diagnosis: "Стенокардия",
    admittedAt: "2026-05-08",
    isCritical: true,
    doctorId: "doctor-1",
  },
  {
    id: "patient-15",
    fullName: "Екатерина Фролова",
    age: 30,
    diagnosis: "Пиелонефрит",
    admittedAt: "2026-05-07",
    isCritical: false,
    doctorId: "doctor-9",
  },
];